const BUSINESS_CATEGORIES = [
  "Select Business Category",
  "Accounting & Tax Services",
  "Arts, Culture & Entertainment",
  "Auto Sales & Service",
  "Banking & Finance",
  "Business Services",
  "Community Organizations",
  "Dentists & Orthodontists",
  "Education",
  "Health & Wellness",
  "Health Care",
  "Home Improvement",
  "Insurance",
  "Internet & Web Services",
  "Legal Services",
  "Lodging & Travel",
  "Marketing & Advertising",
  "News & Media",
  "Pet Services",
  "Real Estate",
  "Restaurants & Nightlife",
  "Shopping & Retail",
  "Sports & Recreation",
  "Transportation",
  "Utilities",
  "Wedding, Events & Meetings",
];
export default BUSINESS_CATEGORIES;
